@startuml Class Diagram

' View
class Menu {
    - IMenuState currentMenuState
    - float secondsBeforeCleaningMenu
    - Input input

    + void runMenu()
    + void cleanMenu()
    + void setState()
}

class TextColor {
    + static final String WHITE_BOLD
    + static final String GREEN_BOLD
    + static final String RED_BOLD
    + static final String BLUE_BOLD
}

' Controller
class Input {
    - Scanner sc
    + String getAlphabeticInput()
    + String getStringInput()
    + Integer getIntegerInput()
}

' Model
package Model {
    top to bottom direction
    
    interface IItemData<T> {
    ' Implementação para cada tipo
    + void createItem(Input input)
    + void displayItemInfo(int itemIndex)
    + void listAllItens()
    + void updateItem(int itemIndex, Input input)
    + String getItemName()

    ' Implementação comum a todos
    + T getItemFromList(int itemIndex)
    + boolean hasItem()
    + ArrayList<T> getItemList()
    + void registerItem(T item) 
    + void deleteItem(int itemIndex || T item)
    + void loadItens()
    }

    class ItemDataManager {
        ' Implementados  
        + void deleteItem(int itemIndex)
        + void registerItem(T item)
        + boolean hasItem()
        + getItemFromList(int itemIndex)

        + abstract void listAllItens();
        + abstract void displayItemInfo(int itemIndex);
        + abstract boolean createItem(Input input);
        + abstract ArrayList<T> getItemList();
        + abstract String getItemName();
    }

    class AnimalData {
        ' T = Animal
        - ArrayList<Animal> registedAnimals
        - static final String ITEM_NAME

        + boolean createItem(Input input)
        + ArrayList<Animal> getItemList
        + void updateItem(int itemIndex, Input input)
        + void listAllItens()
        + void getItemName()
    }

    class ReportData {
        ' T = Report
        - ArrayList<Report> registedReports
        - static final String ITEM_NAME

            + boolean createItem(Input input)
        + ArrayList<Report> getItemList
        + void updateItem(int itemIndex, Input input)
        + void listAllItens()
        + void getItemName()
    }

    class Animal {
        - String popularName
        - String cientificName
        - String habitat
        - String locationInZoo

        + boolean update()
    }

    class Report {
        - String reportName
        - String reportText
        - Animal reportedAnimal
    }

    ' Menu Management 
    package MenuManagement {
        left to right direction
        
        interface IMenuState {
        + void writeMenu()
        + void doMenuOperations(Input input)
        + IMenuState changeMenu()
        }

        class MainMenuState {
            - Integer userOption
            - Integer nextMenuValue
        } 

        class VisitorMainMenuState {
            - Integer userOption
            - Integer nextMenuValue
        }

        class AdminMainMenuState {
            - Integer userOption
            - Integer nextMenuValue
        }

        class QueryItemMenuState {
            - Integer userOption
            - Integer nextMenuValue
            - IMenuState lastMenu
            - IItemData itemData
            
            + QueryItemMenuState(IMenuState lastMenu, IItemData itemData)
        }

        class CreateItemMenuState {
            - Integer userOption
            - Integer nextMenuValue
            - IMenuState lastMenu
            - IItemData itemData

            + CreateItemMenuState(IMenuState lastMenu, IItemData itemData)
        }

        class UpdateItemMenuState {
            - Integer userOption
            - Integer nextMenuValue
            - IMenuState lastMenu
            - IItemData itemData
            
            + UpdateItemMenuState(IMenuState lastMenu, IItemData itemData)
        }

        class DeleteItemMenuState {
            - Integer userOption
            - Integer nextMenuValue
            - IMenuState lastMenu
            - IItemData itemData

            + DeleteItemMenuState(IMenuState lastMenu, IItemData itemData)
        }
    }
}

' Relacionamentos

' Associação
TextColor -- Menu
Input -- Menu

' Implementação (Interfaces)

IMenuState <|. MainMenuState
IMenuState <|. VisitorMainMenuState
IMenuState <|. AdminMainMenuState
IMenuState <|.. QueryItemMenuState
IMenuState <|.. CreateItemMenuState
IMenuState <|.. UpdateItemMenuState
IMenuState <|.. DeleteItemMenuState

ItemDataManager ..|> IItemData

' Herança
AnimalData --|> ItemDataManager : "T = Animal"
ReportData --|> ItemDataManager : "T = Report"

' Composição 
Menu *- IMenuState

AnimalData *- Animal
ReportData *- Report

IItemData -* QueryItemMenuState
IItemData -* CreateItemMenuState
IItemData -* UpdateItemMenuState
IItemData -* DeleteItemMenuState

@enduml