@startuml Diagrama de Casos de Uso

    ' Atores (quem vai interagir com o sistema)
    actor "Visitante" as visitante
    actor "Funcionário" as funcionario 

    ' O sistema em si e suas funcionalidades
    rectangle System {
        usecase "Consultar Animais" as UC1
        usecase "Relatar erro" as UC2
        usecase "Adicionar Animal" as UC3
        usecase "Atualizar Animal" as UC4
        usecase "Excluir Animal" as UC5
        usecase "Verificar Relatos" as UC6
        usecase "Excluir relato de erro" as UC7
        usecase "Persistir dados" as UC8
    }

    
    ' Casos de uso do Visitante
    visitante -down- UC1
    
    ' Casos de uso do Funcionário
    funcionario -down- UC1
    funcionario -down- UC3
    funcionario -down- UC4
    funcionario -down- UC5
    funcionario -down- UC6

    ' Relacionamentos entre Casos de Uso
    UC1 <.. UC2 : "<<extends>>"
    
    UC6 <.. UC7 : "<<extends>>"
    note on link
        Caso o relato não seja mais útil
    end note
    
    UC3 ..> UC8 : "<<includes>>"
    UC4 ..> UC8 : "<<includes>>"
    UC5 ..> UC8 : "<<includes>>"
    UC2 ..> UC8 : "<<includes>>"


@enduml